@startgantt
title Planificación temporal del Trabajo de Fin de Grado
Project starts 2024-01-01

[Fase 1 - Exploración inicial] lasts 90 days
[Fase 2 - Diseño y arquitectura] lasts 90 days
[Fase 3 - Implementación del núcleo] lasts 150 days
[Fase 4 - Herramientas de editor] lasts 120 days
[Fase 5 - Pruebas y documentación] lasts 60 days

[Fase 2 - Diseño y arquitectura] starts at [Fase 1 - Exploración inicial]'s end
[Fase 3 - Implementación del núcleo] starts at [Fase 2 - Diseño y arquitectura]'s end
[Fase 4 - Herramientas de editor] starts at [Fase 3 - Implementación del núcleo]'s end
[Fase 5 - Pruebas y documentación] starts at [Fase 4 - Herramientas de editor]'s end

@endgantt